# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=64)),
                ('lastName', models.CharField(default='', max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('hashKey', models.CharField(max_length=256, null=True)),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
