# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180221_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hashKey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registered',
        ),
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
