# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
